//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUOIKI_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public string ID { get; set; }
        public string Assignee { get; set; }
        public string Assigner { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public System.DateTime StartingTime { get; set; }
        public System.DateTime EndingTime { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string TeamID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
